FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 go build -o controller ./cmd/controller

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/controller .

CMD ["./controller"]

